<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-01T19:42:54 IST" name="Default suite" finished-at="2024-04-01T19:43:15 IST" duration-ms="21523">
    <groups>
    </groups>
    <test started-at="2024-04-01T19:42:54 IST" name="Default test" finished-at="2024-04-01T19:43:15 IST" duration-ms="21523">
      <class name="Task.Task.DDExcel">
        <test-method signature="DemoProject(java.lang.String,java.lang.String)[pri:0, instance:Task.Task.DDExcel@436813f3]" started-at="2024-04-01T19:42:55 IST" name="DemoProject" data-provider="testdata" finished-at="2024-04-01T19:43:06 IST" duration-ms="10396" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[standard_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[secret_sauce]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method is-config="true" signature="ProgramTermination()[pri:0, instance:Task.Task.DDExcel@436813f3]" started-at="2024-04-01T19:43:06 IST" name="ProgramTermination" finished-at="2024-04-01T19:43:06 IST" duration-ms="419" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
        <test-method signature="DemoProject(java.lang.String,java.lang.String)[pri:0, instance:Task.Task.DDExcel@436813f3]" started-at="2024-04-01T19:43:06 IST" name="DemoProject" data-provider="testdata" finished-at="2024-04-01T19:43:15 IST" duration-ms="8560" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[abc_user]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[abc]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Invalid credentials expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Invalid credentials expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at Task.Task.DDExcel.DemoProject(DDExcel.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DemoProject -->
        <test-method is-config="true" signature="ProgramTermination()[pri:0, instance:Task.Task.DDExcel@436813f3]" started-at="2024-04-01T19:43:15 IST" name="ProgramTermination" finished-at="2024-04-01T19:43:15 IST" duration-ms="379" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProgramTermination -->
      </class> <!-- Task.Task.DDExcel -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
